### ISSUE TITLE
Ultra96 Board with PYNQ Connectivity Issues

### ISSUE THREAD

**Issue by yasaspeiris** [Avnet/Ultra96-PYNQ#10]
Hey!
I have been working with my Ultra96 board with PYNQ v2.3 for a few days now, but suddenly the wifi access point does not appear when I turn on the board. I cannot also connect via USB. 
After booting the DONE LED turns on and the the Linux heart beat LED begins to blink so it couldn't be a SD issue right? I reformatted the SD and flashed PYNQ again but still no luck.

**Comment by focalplane** [comment]
The usb connection does not work at all?  Normally the USB host connection is multi-functional, one of the functions is a serial port which PYNQ sets up a console for.  Does that much work?  If so you can use that to poke around and see what is going on, look at ifconfig etc.
