### ISSUE TITLE
Ultra96 Vivado Project for Base Hardware

### ISSUE THREAD

**Issue by hcook95** [Avnet/Ultra96-PYNQ#12]
Where could I find the Vivado project for the base hardware?

**Comment by yunqu** [comment]
There are multiple ways. You can extract the bsp and look the hardware project from there. An easier way is to look at our sensors96b overlay. That is the bitstream loaded during boot-up.

**Comment by focalplane** [comment]
Hi, I just updated the instructions to show you how to create a BSP from scratch that pulls in the boot up hardware design!
