### ISSUE TITLE
where is ultra96-v2 bsp????

### ISSUE THREAD

**Issue by zwpls** [Avnet/Ultra96-PYNQ#31]
In the development I want to get ultra96-2 BSP source code package

I tried

xilinx-ultra96-reva-v2018.2-final.bsp from xilinx

Ultra96-V1 - PetaLinux 2018.2 BSP
Ultra96-V1 - PetaLinux 2018.3 BSP 

 
and
sensors96b_v2.bsp
from
https://github.com/Avnet/Ultra96-PYNQ  imagev2.4_v2 branch
but None of them can walk normally
so
where is ultra96_v2 bsp??????

**Comment by focalplane** [comment]
There is a minimal BSP here for PYNQ, it's named sensors96b_v2.bsp for U96 V1 it is sensors96b_v1.bsp

I fixed a confusing part of the readme but the bsp's have always been there since June.  Make sure you are on the right branch image_v2.4_v2 or master.  They are under ./Ultra96.
