### ISSUE TITLE
Ultra96 V2 2.5 Bluetooth can‘t scan any devices

### ISSUE THREAD

**Issue by sazczmh** [Avnet/Ultra96-PYNQ#58]
Hi,

In the ultra96 V2 2.5 image, I could not use bluetooth. the bluetooth states as follows

```
Controller F8:F0:05:C3:1A:5F (public)
Name: pynq
Alias: pynq
Class: 0x00000000
Powered: yes
Discoverable: yes
Pairable: yes
UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
Modalias: usb:v1D6Bp0246d0530
Discovering: yes
```

but i can‘t scan any devices?

```
[bluetooth]# scan on
Discovery started
[CHG] Controller F8:F0:05:C3:1A:5F Discovering: yes
[bluetooth]# devices
[bluetooth]# scan off
[CHG] Controller F8:F0:05:C3:1A:5F Discovering: no
Discovery stopped
[bluetooth]#
```

**Comment by zedhed** [comment]
Is this for a specific issue that are you providing a solution for?  

I don't see a full list of instructions to recreate your issue or solution which makes it difficult for us to provide meaningful support for your issue.

If you are seeing support, I suggest that you instead visit the support forums for Ultra96 on the Element14 site here where the engineering community can better address your issue:
https://www.element14.com/community/community/designcenter/zedboardcommunity/zedboard-forums/ultra96-hardware-design-forum

There are some posts available there which cover the use of Bluetooth:
https://www.element14.com/community/thread/73916/l/bluetooth-on-ultra96v2

Best Regards,

-Kevin
