### ISSUE TITLE
Incomplete kernel headers in v2.6 (Ultra96v2 image)

### ISSUE THREAD

**Issue by combinatorylogic** [Avnet/Ultra96-PYNQ#71]
How to reproduce:
`git clone https://github.com/ikwzm/udmabuf.git`
`cd udmabuf`
`make`

Apparently `asm/types.h` and a lot more are not in the right place. In v2.5 kernel headers were ok (with the large `/kernel.tgz` tarball) out of the box.

**Comment by yunqu** [comment]
In 2.6 it is just the tarball no longer exists. Others should be the same. I wonder if it is just the path or something is wrong.

**Comment by combinatorylogic** [comment]
Ok, found the solution: just do `make headers_check headers_install scripts` in `/usr/src/kernel`.

**Comment by focalplane** [comment]
Thank you @combinatorylogic and @yunqu!  Seems resolved, makes my life easy.
