### ISSUE TITLE
PMBUS in Ultra96 V2 2.5 

### ISSUE THREAD

**Issue by AnantaBalaji** [Avnet/Ultra96-PYNQ#72]
is there any way by which we can access power rails via pynq pmbus in ultra96 v2. I would like to know if it is possible to measure power via pmbus without flashing the board to v2.6 image?

**Comment by focalplane** [comment]
Hi,

Sorry, no you cannot read the same exact power rails with v2.5 as v2.6.  If you must use v2.5 and read the same rails you would have to merge in the v2.6 changes for that feature and rebuild v2.5.

On the other hand, you can still read some of the available rails when using v2.5, you will have to experiment to see which ones.  See here for a general description of how to do this (note that for v2.6 the Python PYNQ library has changed as well): https://pynq.readthedocs.io/en/v2.5/pynq_package/pynq.pmbus.html
