### ISSUE TITLE
Is an Ubuntu 20 based image in the works?

### ISSUE THREAD

**Issue by balintmaci** [Avnet/Ultra96-PYNQ#73]
Newer ROS versions recommend Ubuntu 20, so with this image we are stuck with older releases.

**Comment by focalplane** [comment]
Major releases of PYNQ are typically done once a year now.  The latest v2.6 was just released a few weeks ago.  The Xilnx PYNQ team decides what to include in the official releases.  That said it is all open source so it can theoretically be done by anyone.  See the [Xilinx PYNQ github](https://github.com/Xilinx/PYNQ) for more info.
