### ISSUE TITLE
Kernel, gcc and modules (v2.6)

### ISSUE THREAD

**Issue by combinatorylogic** [Avnet/Ultra96-PYNQ#77]
Another little issue with kernel in v2.6: it's buit with gcc-9.2.0, which is not available from the PYNQ image. More so, trying to install one from Ubuntu using the usual `add-apt-repository ppa:ubuntu-toolchain-r/test` does not work straight away either (unless `lsb-release` is modified to pretend it's ubuntu18.04, no PPAs can be added).

And since stack guard option is on in this kernel, no module can be built with a gcc below 9. This is a little inconsistency and is relatively easy to fix (just provide gcc-9 out of the box?).

**Comment by yunqu** [comment]
@combinatorylogic This is exactly what we do in DPU: https://github.com/Xilinx/DPU-PYNQ/tree/master/upgrade
