### ISSUE TITLE
desktop now show

### ISSUE THREAD

**Issue by PapaKache** [Avnet/Ultra96-PYNQ#80]
console show login,but cannot show desktop

**Comment by focalplane** [comment]
Please elaborate.  If you are using one, not all mini Displayport to HDMI adapters are compatible.  You should be using an active not passive adapter and not all of those work. I don't have a current adapter to recommend.  The most reliable system is going to be a mini to full size Displayport adapter connected to a Displayport monitor or a monitor that accepts mini displayport.  Normally the fluxbox desktop is started when the system boots.  I have used it for v2.5, I have not personally tried it for U96 v2.6 PYNQ.
