### ISSUE TITLE
Failed to install docker _not sure if it is OS incompatible issue

### ISSUE THREAD

**Issue by royliuyu** [Avnet/Ultra96-PYNQ#81]
I succesfully installed the PYNQ with http://avnet.me/ultra96v2-pynq-image-v2.6
Further, I am going to install docker and then use FINN.
But encountered some errors:
I follow the install instruction via [Install Docker Engine on Ubuntu](https://docs.docker.com/engine/install/ubuntu/), in order to fit the ubuntu contribution codename  with docker's, I revised the codename from _WFH_ to _bionic_ in file of "lsb_release".
But when I install by using command :
![image](https://user-images.githubusercontent.com/47387577/115489376-1df73b00-a22a-11eb-9cff-ff0fa899f546.png)

There is still errors like"

![1](https://user-images.githubusercontent.com/47387577/115488991-6cf0a080-a229-11eb-9525-896f66f91011.png)

I have googled and got some comments said it come from incorrect Ubuntu distribution codename, but I am pretty sure the bionic is the correct name selected.
Is anyone has experienced and gets any solution?

**Comment by schelleg** [comment]
Can you try steps here:
https://discuss.pynq.io/t/docker-xilinx-platforms-pynq/1962

we hardcode versions of those deb packages and have verified docker installs correctly.

**Comment by royliuyu** [comment]
schelleg，
Your URL really works, I amount docker with the guidence successfully.
Thanks
