### ISSUE TITLE
Link to access the Ultra96V2 image is broken.

### ISSUE THREAD

**Issue by gordonro** [Avnet/Ultra96-PYNQ#82]
http://avnet.me/ultra96v2-pynq-image-v2.6  doesn't work,

avnet.me seems to be old or down

**Comment by zedhed** [comment]
Hi @gordonro I just checked this link and it appears to be working for me.  Which browser are you using?

Also, this channel is not monitored regularly.  For better response, please check out our Element14 community which has engineers dedicated to monitoring for posted issues like this one:

https://www.element14.com/community/community/designcenter/zedboardcommunity/zedboard-forums

Best Regards,

-Kevin
