### ISSUE TITLE
I2C1 not Operating at 400KHz

### ISSUE THREAD

**Issue by phishphood** [Avnet/Ultra96-PYNQ#87]
Device tree file pcw.dtsi indicates i2c1 clock frequency of 400000.
Device tree file avnet-ultra96-rev1.dtsi indicates i2c1 clock frequency of 100000.
After build, i2c1operates at 100000. dtc extraction of device tree after build of Pynq 2.7.0 confirms i2c1 clock is being set to 100KHz.
Assumption is that pcw.dtsi was intended to change this parameter to 400000.

**Comment by phishphood** [comment]
Cadence I2C Driver has limitations that may make 400KHz not possible. See 
link -
https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18842160/Cadence+I2C+Driver

**Comment by focalplane** [comment]
Closing, solution was given in prior comment.  Thank you for reaching out with the issue!
