### ISSUE TITLE
Enable Wifi for Ultra96-V2? How ??

### ISSUE THREAD

**Issue by jiapei100** [Avnet/Ultra96-PYNQ#95]
Can you help and take a look at this issue:

[https://discuss.pynq.io/t/i-finally-boot-up-ultra96-v2-using-pynq-but-not-let-me-login/4946](https://discuss.pynq.io/t/i-finally-boot-up-ultra96-v2-using-pynq-but-not-let-me-login/4946)

**Comment by focalplane** [comment]
Answered on PYNQ support forum, closing.
